### PR TITLE
Allow for multiple maintenance templates

### PR DESCRIPTION
**Pull request by tjwallace**
This is useful if you want to serve a different file based on the request content type.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the PR!

This looks like a breaking change, since you have removed the `:maintenance_template_path` setting. Is there a way you could provide backwards compatibility for people that are currently using this variable?

**Comment by tjwallace** [comment]
@mattbrictson yup! I've added backwards compatibility in 61fd8cb

**Comment by mattbrictson** [comment]
Since this project lacks automated tests, I will need to try this out manually on an actual project to make sure I understand how it works. Thanks for the PR and thank you for your patience while I review!

**Comment by mattbrictson** [comment]
Regarding the backwards compatibility: I tried it out and it doesn't work. If I set `:maintenance_template_path` in my `deploy.rb` it always ends up getting overwritten with the default value.

I think the problem is that `defaults:load` runs first, before the user's `deploy.rb` is evaluated.

Maybe a lambda is need to delay execution?

**Comment by tjwallace** [comment]
@mattbrictson good catch! Using a lambda seems to do the trick, see 8272fd3

**Comment by mattbrictson** [comment]
Sorry, I noticed another issue: this also removes `:maintenance_basename` without any apparent replacement. It looks like there is no longer a way to control what the file is named when uploaded to the server (other than changing the name of the template itself)?

This PR seems to be shaping up to being too large of a change for me to merge.

I do like the idea of being able to provide a separate JSON maintenance response. I'm just not sure there is a way to do that in this gem without some fundamental breaking changes.

**Comment by tjwallace** [comment]
@mattbrictson I could change the type of `maintenance_templates` to be an array of tuples with items being the template path and the output basename:

```ruby
set_if_empty :maintenance_templates, -> do
  [
    [
      fetch(:maintenance_template_path, File.expand_path('../../templates/maintenance.html.erb', __FILE__)),
      fetch(:maintenance_basename, 'maintenance')
    ]
  ]
end
```

And then to add a JSON template:

```ruby
append :maintenance_templates, [
  File.expand_path('deploy/maintenance.json.erb', __dir__),
  'maintenance'
]
```

**Comment by mattbrictson** [comment]
Hi @tjwallace, I have my hands full and can't invest much time in this gem at the moment. Sorry! I do still think supporting both HTML and JSON templates is a good idea. Maybe you could publish your own gem with these new features!

In the meantime I will close this PR since it is a bigger change than I can support right now.

**Pull request closed without merging**
